title: files

sections:
  info:
    type: fields
    fields:
      date:
        type: select
        options:
          Fri 13: Fri 13
          Sat 14: Sat 14
          Sun 15: Sun 15
          Mon 16: Mon 16
          Tue 17: Tue 17
          Wed 18: Wed 18
          Thu 19: Thu 19
          Fri 20: Fri 20
          Sat 21: Sat 21
          Sun 22: Sun 22
          Mon 23: Mon 23
        width: 1/3
      tag:
        type: select
        options:
          tagText1: Balabala
          tagText2: Balabala
          tagText3: Balabala
          tagText4: Balabala
          tagText5: Balabala
          tagText6: Balabala
          tagText7: Balabala
          tagText8: Balabala
          tagText9: Balabala
          tagText10: Balabala
          tagText11: Balabala
        width: 1/3
      fileType:
        type: select
        options:
          audio: audio with people's voice
          ambient: ambient sound / field recording
          image: image
          video: video
        width: 1/3
      shortDescription:
        type: text
        width: 1/2
      detailedDescription:
        type: textarea
        width: 1/2
